# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartViewSample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'PNChart'
  # Pods for ChartViewSample

  target 'ChartViewSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChartViewSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
