# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end

workspace 'Samples.xcworkspace'
target 'Samples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Samples
  pod 'CocoaAsyncSocket'
  # MQTT
  pod 'CocoaMQTT', '~> 2.1.6'
  # CBOR
  pod 'SwiftCBOR', '~> 0.4.6'
  pod 'MJRefresh', '~> 3.7.5'
  
  target 'SamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SamplesUITests' do
    # Pods for testing
  end

end

target 'HzgTools' do
  project '../../HzgTools/HzgTools.xcodeproj'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # MQTT
  pod 'CocoaMQTT', '~> 2.1.6'
  # CBOR
  pod 'SwiftCBOR', '~> 0.4.6'
  pod 'MJRefresh', '~> 3.7.5'
end
