# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartViewSampleSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PNChart'
  
  # Pods for ChartViewSampleSwift

  target 'ChartViewSampleSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChartViewSampleSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
